(setq *abbrev-command-list* '("pur"  "ra"   "rg"   "rga"  "sk"   "tm"   "vs"   "z"    "za"   "zc"   "zd"   "ze"   "zp"   "zv"
                  "zw"   "fr"   "f"    "chd"  "ch"   "s"    "l"    "a"    "o"    "c"    "e"    "co"   "cp"   "m"
                  "ro"   "gr_on_off"   "tr"   "ex"   "rec"  "mi"   "el"   "br"   "u"    "undo" "sc"   "oops" "di"
                  "id"   "ma"   "le"   "op"   "h"    "dt"   "pe"   "bo"   "ar"   "li"   "x"    "j"    "b"    "ps"
                  "ms"   "git"  "vl"   "vu"   "lou"))
;;;;(opech_cmds-str *abbrev-opech*)

(defun c:חדך() (c:pur))
(defun c:ךפ() (c:ra))
(defun c:ךן() (c:rg))
(defun c:ךןפ() (c:rga))
(defun c:ûכ() (c:sk))
(defun c:וü() (c:tm))
(defun c:לû() (c:vs))
(defun c:ÿ() (c:z))
(defun c:ÿפ() (c:za))
(defun c:ÿס() (c:zc))
(defun c:ÿג() (c:zd))
(defun c:ÿף() (c:ze))
(defun c:ÿח() (c:zp))
(defun c:ÿל() (c:zv))
(defun c:ÿצ() (c:zw))
(defun c:אך() (c:fr))
(defun c:א() (c:f))
(defun c:סנג() (c:chd))
(defun c:סנ() (c:ch))
(defun c:û() (c:s))
(defun c:ה() (c:l))
(defun c:פ() (c:a))
(defun c:ש() (c:o))
(defun c:ס() (c:c))
(defun c:ף() (c:e))
(defun c:סש() (c:co))
(defun c:סח() (c:cp))
(defun c:ü() (c:m))
(defun c:ךש() (c:ro))
(defun c:ןך_שע_שאא() (c:gr_on_off))
(defun c:וך() (c:tr))
(defun c:ףק() (c:ex))
(defun c:ךףס() (c:rec))
(defun c:üר() (c:mi))
(defun c:ףה() (c:el))
(defun c:טך() (c:br))
(defun c:ד() (c:u))
(defun c:דעגש() (c:undo))
(defun c:ûס() (c:sc))
(defun c:ששחû() (c:oops))
(defun c:גר() (c:di))
(defun c:רג() (c:id))
(defun c:üפ() (c:ma))
(defun c:הף() (c:le))
(defun c:שח() (c:op))
(defun c:נ() (c:h))
(defun c:גו() (c:dt))
(defun c:חף() (c:pe))
(defun c:טש() (c:bo))
(defun c:פך() (c:ar))
(defun c:הר() (c:li))
(defun c:ק() (c:x))
(defun c:מ() (c:j))
(defun c:ט() (c:b))
(defun c:חû() (c:ps))
(defun c:üû() (c:ms))
(defun c:ןרו() (c:git))
(defun c:לה() (c:vl))
(defun c:לד() (c:vu))
(defun c:השד() (c:lou))

(princ "Loaded project abrev.\n")