;;;;;;("ltp" "Загрузка шрифтов линий." "Настройка")
(defun c:ltp  ()
  (command "_ltscale" "1")
  (command "_psltscale" "1")
  (command "_-linetype" "_load" "*" (strcat (acad_sup) "/lines/eskd"))
  (while (= 1 (getvar "CMDACTIVE")) (command ""))
  (command "_regen")
  (princ))